#! /usr/bin/env bash

source bszi3b-shared.bash &> /dev/null || source ${0%/*}/bszi3b-shared.bash || exit 1

ICON_LO=${ICON_LO:-"< "}
ICON_MID=${ICON_MID:-"<l "}
ICON_HI=${ICON_HI:-"<ll "}

case "$BLOCK_BUTTON" in
1 | 4) ompl volume add 0.05 ;;
3 | 5) ompl volume sub 0.05 ;;
esac

state=$(ompl print status)

if [ "$state" = "playing" ]; then
    COLOR=$COLOR_HI
elif [ "$state" = "paused" ]; then
    COLOR=$COLOR_LO
elif [ "$state" = "stopped" ]; then
    COLOR=""
else
    COLOR=$COLOR_ERR
fi

volume=$(ompl volume get)

if (( ${volume#*.} <= 33 )); then
    icon=$ICON_LO
elif (( ${volume#*.} >= 66 )); then
    icon=$ICON_HI
else
    icon=$ICON_MID
fi

LONG=$icon$volume

i3bprint
