#! /usr/bin/env bash

source bszi3b-shared.bash &> /dev/null || source ${0%/*}/bszi3b-shared.bash || exit 1

TAGSTRING=${TAGSTRING:-"<title><artist| / <artist>><album| / <album>>"}
TAGSTRING_SHORT=${TAGSTRING_SHORT:-"title"}

VOL_SIGNAL=${VOL_SIGNAL:-""}

ICON_PAUSE=${ICON_PAUSE:-""}
ICON_PLAY=${ICON_PLAY:-""}
ICON_STOP=${ICON_STOP:-""}

assertval $TAGSTRING TAGSTRING

tagstring=$(ompl print tagstring "$TAGSTRING")
[ -z "$tagstring" ] && i3berr "OMPL Off"

[ -z "$TAGSTRING_SHORT" ] && TAGSTRING_SHORT="$TAGSTRING"
tagstring_short=$(ompl print tagstring "$TAGSTRING_SHORT")
[ -z "$tagstring_short" ] && i3berr "OMPL TAGSTRING_SHORT Empty"

case "$BLOCK_BUTTON" in
1) ompl play-pause ;;
3) ompl stop ;;
4) ompl next ;;
5) ompl previous ;;
esac

state=$(ompl print status)

if [ "$state" = "playing" ]; then
    icon=$ICON_PLAY
    COLOR=$COLOR_HI
elif [ "$state" = "paused" ]; then
    icon=$ICON_PAUSE
    COLOR=$COLOR_LO
elif [ "$state" = "stopped" ]; then
    icon=$ICON_STOP
else
    icon="[?]"
    COLOR=$COLOR_ERR
fi

LONG=$icon$tagstring
SHORT=$icon$tagstring_short

i3bprint

[ -n $VOL_SIGNAL ] && pkill -RTMIN+$VOL_SIGNAL i3blocks

