#! /usr/bin/env bash

DEVICE=${DEVICE:-"@DEFAULT_AUDIO_SINK@"}

# handy for changing icon on microphones
PREFIX=${PREFIX:-""}

ICON_LO=${ICON_LO:-"<) "}
ICON_MID=${ICON_MID:-"<)) "}
ICON_HI=${ICON_HI:-"<))) "}
ICON_MUTE=${ICON_MUTE:-"< "}

COLOR_LO=${COLOR_LO:-"#2EAFFF"}
COLOR_MID=${COLOR_MID:-""}
COLOR_HI=${COLOR_HI:-"#D3A350"}
COLOR_MUTE=${COLOR_MUTE:-"#73BC6F"}

COLOR_ERROR=${COLOR_ERROR:-"#FF898E"}

case "$BLOCK_BUTTON" in
1) wpctl set-mute $DEVICE toggle ;;
3) wpctl set-volume $DEVICE 1.0 ;;
4) wpctl set-volume $DEVICE 0.05+ ;;
5) wpctl set-volume $DEVICE 0.05- ;;
esac

volume=$(wpctl get-volume $DEVICE)
volume=${volume##*:}
muted=${volume##* }
volume=${volume%%\[MUTED\]}

if [ "$muted" == "[MUTED]" ]; then
    icon=$ICON_MUTE
    color=$COLOR_MUTE
else
    if (($(echo "$volume < 1.0" | bc))); then
        icon=$ICON_LO
        color=$COLOR_LO
    elif (($(echo "$volume > 1.0" | bc))); then
        icon=$ICON_HI
        color=$COLOR_HI
    else
        icon=$ICON_MID
        color=$COLOR_MID
    fi
fi

if [ "$volume" != "" ]; then
    echo $PREFIX$icon$volume
    echo $PREFIX$icon$volume
    if [ "$color" != "" ]; then
        echo $color
    fi
else
    echo "WPCTL Err"
    echo "WPCTL Err"
    echo $COLOR_ERROR
fi

exit 0
